version: '3.8'

services:
  web:
    build: ./web_front
    ports:
      - "8080:80"

  db:
    build: ./sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_password_here